In [99]:
import tensorflow as tf
import numpy as np

In [100]:
tf.__version__

'2.0.0'

# Constants/Tensors:

In [101]:
tensor = tf.constant([[10, 20], [30, 40]])

In [102]:
tensor

<tf.Tensor: id=160, shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]])>

In [103]:
tensor.get_shape()

TensorShape([2, 2])

In [104]:
tensor + 7

<tf.Tensor: id=162, shape=(2, 2), dtype=int32, numpy=
array([[17, 27],
       [37, 47]])>

In [105]:
np.square(tensor)

array([[ 100,  400],
       [ 900, 1600]], dtype=int32)

In [106]:
np.sqrt(tensor)

array([[3.16227766, 4.47213595],
       [5.47722558, 6.32455532]])

In [107]:
tensor * 7

<tf.Tensor: id=164, shape=(2, 2), dtype=int32, numpy=
array([[ 70, 140],
       [210, 280]])>

In [108]:
tensor.numpy()

array([[10, 20],
       [30, 40]])

In [109]:
numpy_tensor = np.array([[23,  4], [32, 51]])

In [110]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [111]:
tensor_from_numpy

<tf.Tensor: id=165, shape=(2, 2), dtype=int32, numpy=
array([[23,  4],
       [32, 51]])>

In [112]:
tensor2 = tf.constant([[11, 25], [35, 49]])

In [113]:
np.dot(tensor, tensor2)

array([[ 810, 1230],
       [1730, 2710]])

# Operations with variables

In [114]:
tf2_variable = tf.Variable([[1., 2., 3.], [4., 5., 6.]])
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)>

In [115]:
tf2_variable.numpy()

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [116]:
tf2_variable[0, 2].assign(500)

<tf.Variable 'UnreadVariable' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 500.],
       [  4.,   5.,   6.]], dtype=float32)>

In [117]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 3) dtype=float32, numpy=
array([[  1.,   2., 500.],
       [  4.,   5.,   6.]], dtype=float32)>

In [118]:
tf_string = tf.constant("TensorFlow")
tf_string

<tf.Tensor: id=184, shape=(), dtype=string, numpy=b'TensorFlow'>

In [119]:

tf.strings.length(tf_string)

<tf.Tensor: id=185, shape=(), dtype=int32, numpy=10>

In [120]:

tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: id=189, shape=(10,), dtype=int32, numpy=array([ 84, 101, 110, 115, 111, 114,  70, 108, 111, 119])>

In [121]:
tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])

In [122]:
for string in tf_string_array:
  print(string)

tf.Tensor(b'TensorFlow', shape=(), dtype=string)
tf.Tensor(b'Deep Learning', shape=(), dtype=string)
tf.Tensor(b'AI', shape=(), dtype=string)


In [123]:
if tf.test.is_gpu_available():
    with tf.device("/gpu:0"):
        tf_string_array = tf.constant(["TensorFlow", "Deep Learning", "AI"])
    print(tf_string_array.device)